# Quick test version using emptyDir (data won't persist)
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
stringData:
  SA_PASSWORD: "YourStrong!Passw0rd"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-test
  template:
    metadata:
      labels:
        app: sqlserver-test
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: SA_PASSWORD
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
        - name: sqlserver-data
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserver-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-test-service
spec:
  selector:
    app: sqlserver-test
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
