FROM apache/superset:4.0.0

ARG ORACLEDB_VERSION=3.3.0
ARG PYMSSQL_VERSION=2.3.7

USER root

# Installation des dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    libaio1 \
    && rm -rf /var/lib/apt/lists/*

# Installation des drivers avec versions spécifiées
RUN pip install --no-cache-dir \
    oracledb==${ORACLEDB_VERSION} \
    pymssql==${PYMSSQL_VERSION}

USER superset
