FROM apache/superset:4.0.0

USER root

# Installation des dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    libaio1 \
    && rm -rf /var/lib/apt/lists/*

# Copie du fichier requirements pour les drivers
COPY requirements-drivers.txt /tmp/requirements-drivers.txt

# Installation des drivers via requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements-drivers.txt \
    && rm /tmp/requirements-drivers.txt

USER superset
