# Configuration Superset avec image personnalisée
image:
  repository: dimproject/superset-learning
  tag: requirements
  pullPolicy: IfNotPresent

# Configuration du service pour Minikube
service:
  type: NodePort
  port: 8088
  nodePort:
    http: 30088
  annotations: {}

# Configuration des réplicas
replicaCount: 1

# Variables d'environnement
# envFromSecret: superset-env-secret  # Commenté car le secret n'existe pas
envFromSecrets: []

# Configuration de la base de données interne
postgresql:
  enabled: true  # PostgreSQL intégré pour Superset
  auth:
    postgresPassword: "superset123"
    username: "superset"
    password: "superset123"
    database: "superset"
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Configuration de l'initialisation avec drivers
init:
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@superset.com
    password: FormationSupersetAdmin002
  createAdmin: true

# Ressources
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Configuration personnalisée
configOverrides:
  superset_config.py: |
    import os
    import sys
    import oracledb
    oracledb.version = "8.3.0"
    sys.modules["cx_Oracle"] = oracledb
    import cx_Oracle

    # Configuration de base
    SECRET_KEY = os.environ.get('SUPERSET_SECRET_KEY', 'your-secret-key-change-in-production')

    # Configuration de la base de données Superset (PostgreSQL intégré)
    SQLALCHEMY_DATABASE_URI = 'postgresql://superset:superset123@superset-postgresql:5432/superset'

# Configuration du secret pour les variables d'environnement
extraSecretEnv:
  SUPERSET_SECRET_KEY: your-secret-key-change-in-production

# Configuration Ingress (désactivé par défaut)
ingress:
  enabled: false

extraConfigs:
  import_datasources.yaml: |
    databases:
    - database_name: "Production SQL Server"
      sqlalchemy_uri: "mssql+pymssql://sa:YourStrong!Passw0rd@sqlserver-service.default.svc.cluster.local:1433"
      allow_file_upload: true
      allow_ctas: true
      allow_cvas: true
      allow_run_async: true
      expose_in_sqllab: true
      tables: []

    - database_name: "PostgreSQL Analytics"
      sqlalchemy_uri: "postgresql://superset_user:superset123@postgresql.default.svc.cluster.local:5432/superset_db"
      allow_file_upload: true
      allow_ctas: true
      allow_cvas: true
      allow_run_async: true
      expose_in_sqllab: true
      tables: []

    - database_name: "Oracle Analytics"
      sqlalchemy_uri: "oracle+cx_oracle://admin:admindimops@database-1.c92oy2osmi5g.us-east-1.rds.amazonaws.com:1521/?service_name=ORCL"
      allow_file_upload: true
      allow_ctas: true
      allow_cvas: true
      allow_run_async: true
      expose_in_sqllab: true
      tables: []
