apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
type: Opaque
stringData:
  ORACLE_PWD: "OraclePassword123"

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  selector:
    app: oracle-db
  ports:
    - name: oracle-port
      protocol: TCP
      port: 1521
      targetPort: 1521
    - name: oracle-em
      protocol: TCP
      port: 5500
      targetPort: 5500
  type: ClusterIP
  clusterIP: None  # Headless service pour StatefulSet

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-db
  labels:
    app: oracle-db
spec:
  serviceName: oracle-service
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle-db
        image: container-registry.oracle.com/database/express:21.3.0-xe
        ports:
        - containerPort: 1521
        - containerPort: 5500
        env:
        - name: ORACLE_PWD
          valueFrom:
            secretKeyRef:
              name: oracle-secret
              key: ORACLE_PWD
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        - name: ORACLE_SID
          value: "XE"
        - name: ORACLE_PDB
          value: "XEPDB1"
        volumeMounts:
        - name: oracle-data
          mountPath: /opt/oracle/oradata
        - name: oracle-backup
          mountPath: /opt/oracle/backup
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        # Commande de démarrage avec gestion de l'initialisation
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  # Attendre que Oracle soit prêt
                  while ! sqlplus -s system/${ORACLE_PWD}@localhost:1521/XE <<< "SELECT 1 FROM DUAL;" > /dev/null 2>&1; do
                    echo "Waiting for Oracle to be ready..."
                    sleep 10
                  done
                  echo "Oracle is ready!"
  volumeClaimTemplates:
  - metadata:
      name: oracle-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi
  - metadata:
      name: oracle-backup
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  
  # Stratégie de mise à jour
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  
  # Politique de gestion des pods
  podManagementPolicy: OrderedReady

---
# Service non-headless pour l'accès externe si nécessaire
apiVersion: v1
kind: Service
metadata:
  name: oracle-external
spec:
  selector:
    app: oracle-db
  ports:
    - name: oracle-port
      protocol: TCP
      port: 1521
      targetPort: 1521
    - name: oracle-em
      protocol: TCP
      port: 5500
      targetPort: 5500
  type: ClusterIP
