{{- if or (.Capabilities.APIVersions.Has "external-secrets.io/v1beta1/ExternalSecret") (.Capabilities.APIVersions.Has "external-secrets.io/v1alpha1/ExternalSecret") -}}
apiVersion: {{ include "ingenico-kafbat.capabilities.external-secret.apiVersion" $ }}
kind: ExternalSecret
metadata:
  name: databases-connections
spec:
  refreshInterval: {{ .Values.global.databases.credentialsExternalSecret.refreshInterval }}
  target:
    creationPolicy: Owner
  secretStoreRef:
    name: {{ .Values.global.databases.credentialsExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.global.databases.credentialsExternalSecret.secretStoreRef.kind }}
  data:
  {{- range $i, $connection := .Values.global.databases.connections }}
    - secretKey: DB_{{ $connection.serverName | replace "-" "_" | upper }}
      remoteRef:
        key: {{ $connection.credentialsSecretStoreKey | default (tpl $.Values.global.databases.defaults.credentialsSecretStoreKeyTemplate $connection) }}
        property: "endpoint"
  {{- end }}
{{- end }}
